{"uuid": "54250e3f-6e50-4bcf-a67c-38de717518df", "children": ["56926308-e9dd-4d66-98e9-f68d06bcc9d3", "c434dde4-2cf6-4ad4-890d-c380d32e9f93", "cc2ddeb9-5d01-432b-a20b-76fc31d79093", "0eb779a4-06b9-498d-baf6-5e44fa32fed2", "7cc7e03c-1dba-4d56-a2d1-f79bd7425803", "01ba68c1-0464-4eb7-9066-1c4045a14560", "feba887b-bbc0-43d9-9f80-544558de3556", "7c3acc4e-280c-4357-a0fb-ea9ef8bf5f5a"], "befores": [{"name": "_Class__pytest_setup_class", "status": "passed", "start": 1595340190499, "stop": 1595340190499}], "afters": [{"name": "_Class__pytest_setup_class::0", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\code_all\\\\AutoTest_all\\\\ATScripts-master\\\\report\\\\report.html'\n", "trace": "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 796, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\python.py\", line 726, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\python.py\", line 660, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\code_all\\AutoTest_all\\ATScripts-master\\testcase\\test_case.py\", line 41, in teardown_class\n    EmailHandler().send_email()\n  File \"C:\\code_all\\AutoTest_all\\ATScripts-master\\lib\\EmailHandler.py\", line 45, in send_email\n    send_content = self.read_report()  # 获取测试报告\n  File \"C:\\code_all\\AutoTest_all\\ATScripts-master\\lib\\EmailHandler.py\", line 20, in read_report\n    f = open(conf.TEST_CASE_REPORT_PATH, 'rb')\n"}, "start": 1595340207262, "stop": 1595340210535}], "start": 1595340190499, "stop": 1595340210535}